import { chromium } from '@playwright/test';
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
const b=await chromium.launch(); const p=await b.newPage();
const errs=[];
p.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
p.on('pageerror',e=>errs.push('PAGEERR: '+e.message+'\n'+(e.stack||'').split('\n').slice(0,4).join('\n')));
await p.goto('http://localhost:5274/?physics=collision',{waitUntil:'networkidle'});
await sleep(2000);
const has=await p.evaluate(()=>!!window.__tfPhysics);
const n=await p.evaluate(()=>document.querySelectorAll('[data-body-id]').length);
console.log('__tfPhysics set:', has, 'body elements:', n);
console.log('ERRORS:\n'+(errs.slice(0,4).join('\n---\n')||'none'));
await b.close();
